site_name: MetaRPC MT4 C# Documentation

nav:
  - Home: index.md
  - API Reference: api/mt4_term_api/MT4Account
  - Account Information: 
      -ShowAccountSummary: Account/ShowAccountSummary.md
  - Order Operations: 

  

- Streaming:


  - Market Info:

  - Stream Quotes:



theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - palette.toggle
    - palette.auto

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
