// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt4-term-api-connection.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt4_term_api {
  public static partial class Connection
  {
    static readonly string __ServiceName = "mt4_term_api.Connection";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ConnectExRequest> __Marshaller_mt4_term_api_ConnectExRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ConnectExRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ConnectExReply> __Marshaller_mt4_term_api_ConnectExReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ConnectExReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ConnectRequest> __Marshaller_mt4_term_api_ConnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ConnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ConnectReply> __Marshaller_mt4_term_api_ConnectReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ConnectReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ConnectProxyRequest> __Marshaller_mt4_term_api_ConnectProxyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ConnectProxyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ConnectProxyReply> __Marshaller_mt4_term_api_ConnectProxyReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ConnectProxyReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CheckConnectRequest> __Marshaller_mt4_term_api_CheckConnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CheckConnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CheckConnectReply> __Marshaller_mt4_term_api_CheckConnectReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CheckConnectReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.DisconnectRequest> __Marshaller_mt4_term_api_DisconnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.DisconnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.DisconnectReply> __Marshaller_mt4_term_api_DisconnectReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.DisconnectReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ReconnectRequest> __Marshaller_mt4_term_api_ReconnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ReconnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ReconnectReply> __Marshaller_mt4_term_api_ReconnectReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ReconnectReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.GetBrokerServersByBrokerNameRequest> __Marshaller_mt4_term_api_GetBrokerServersByBrokerNameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.GetBrokerServersByBrokerNameRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.GetBrokerServersByBrokerNameReply> __Marshaller_mt4_term_api_GetBrokerServersByBrokerNameReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.GetBrokerServersByBrokerNameReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.GetIdRequest> __Marshaller_mt4_term_api_GetIdRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.GetIdRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.GetIdReply> __Marshaller_mt4_term_api_GetIdReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.GetIdReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.ConnectExRequest, global::mt4_term_api.ConnectExReply> __Method_ConnectEx = new grpc::Method<global::mt4_term_api.ConnectExRequest, global::mt4_term_api.ConnectExReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConnectEx",
        __Marshaller_mt4_term_api_ConnectExRequest,
        __Marshaller_mt4_term_api_ConnectExReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.ConnectRequest, global::mt4_term_api.ConnectReply> __Method_Connect = new grpc::Method<global::mt4_term_api.ConnectRequest, global::mt4_term_api.ConnectReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_mt4_term_api_ConnectRequest,
        __Marshaller_mt4_term_api_ConnectReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.ConnectProxyRequest, global::mt4_term_api.ConnectProxyReply> __Method_ConnectProxy = new grpc::Method<global::mt4_term_api.ConnectProxyRequest, global::mt4_term_api.ConnectProxyReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConnectProxy",
        __Marshaller_mt4_term_api_ConnectProxyRequest,
        __Marshaller_mt4_term_api_ConnectProxyReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.CheckConnectRequest, global::mt4_term_api.CheckConnectReply> __Method_CheckConnect = new grpc::Method<global::mt4_term_api.CheckConnectRequest, global::mt4_term_api.CheckConnectReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckConnect",
        __Marshaller_mt4_term_api_CheckConnectRequest,
        __Marshaller_mt4_term_api_CheckConnectReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.DisconnectRequest, global::mt4_term_api.DisconnectReply> __Method_Disconnect = new grpc::Method<global::mt4_term_api.DisconnectRequest, global::mt4_term_api.DisconnectReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Disconnect",
        __Marshaller_mt4_term_api_DisconnectRequest,
        __Marshaller_mt4_term_api_DisconnectReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.ReconnectRequest, global::mt4_term_api.ReconnectReply> __Method_Reconnect = new grpc::Method<global::mt4_term_api.ReconnectRequest, global::mt4_term_api.ReconnectReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Reconnect",
        __Marshaller_mt4_term_api_ReconnectRequest,
        __Marshaller_mt4_term_api_ReconnectReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.GetBrokerServersByBrokerNameRequest, global::mt4_term_api.GetBrokerServersByBrokerNameReply> __Method_GetBrokerServersByBrokerName = new grpc::Method<global::mt4_term_api.GetBrokerServersByBrokerNameRequest, global::mt4_term_api.GetBrokerServersByBrokerNameReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBrokerServersByBrokerName",
        __Marshaller_mt4_term_api_GetBrokerServersByBrokerNameRequest,
        __Marshaller_mt4_term_api_GetBrokerServersByBrokerNameReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.GetIdRequest, global::mt4_term_api.GetIdReply> __Method_GetId = new grpc::Method<global::mt4_term_api.GetIdRequest, global::mt4_term_api.GetIdReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetId",
        __Marshaller_mt4_term_api_GetIdRequest,
        __Marshaller_mt4_term_api_GetIdReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt4_term_api.Mt4TermApiConnectionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Connection</summary>
    [grpc::BindServiceMethod(typeof(Connection), "BindService")]
    public abstract partial class ConnectionBase
    {
      /// <summary>
      /// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck",
      ///   "mtClusterName": "FreshForex-Demo"
      /// }  
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.ConnectExReply> ConnectEx(global::mt4_term_api.ConnectExRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Creates terminal connection to the MT4 server and returns Guid of it
      /// [DefaultValues]
      /// {
      ///   "user": "501401178",
      ///   "password": "v8gctta",
      ///   "host": "mt4-demo.roboforex.com",
      ///   "port": "443",
      ///   "baseChartSymbol": "EURUSD",  
      ///   "waitForTerminalIsAlive": "true"
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.ConnectReply> Connect(global::mt4_term_api.ConnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Connect to account with user, password, host, port.
      /// [DefaultValues] 
      /// { 
      ///  "user": "500476959", 
      ///  "password": "ehj4bod", 
      ///  "host": "mt4-demo.roboforex.com", 
      ///  "port": "443",
      ///  "proxyUser": "ProxyUser123", 
      ///  "proxyPassword": "qwerty123", 
      ///  "proxyHost": "65.108.126.217", 
      ///  "proxyPort": "1080", 
      ///  "proxyType": "Socks5" 
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.ConnectProxyReply> ConnectProxy(global::mt4_term_api.ConnectProxyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Checks if terminal connection to MT4 server is alive
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.CheckConnectReply> CheckConnect(global::mt4_term_api.CheckConnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Close terminal connection to MT4 server
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.DisconnectReply> Disconnect(global::mt4_term_api.DisconnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// If you need to recreate terminal instance with the same id
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.ReconnectReply> Reconnect(global::mt4_term_api.ReconnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.GetBrokerServersByBrokerNameReply> GetBrokerServersByBrokerName(global::mt4_term_api.GetBrokerServersByBrokerNameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates a deterministic GUID from user and password.
      /// The same user/password combination always produces the same GUID.
      /// Use this GUID as the 'id' header for Connect and other endpoints.
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck"
      /// }
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.GetIdReply> GetId(global::mt4_term_api.GetIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Connection</summary>
    public partial class ConnectionClient : grpc::ClientBase<ConnectionClient>
    {
      /// <summary>Creates a new client for Connection</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ConnectionClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Connection that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ConnectionClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ConnectionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ConnectionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck",
      ///   "mtClusterName": "FreshForex-Demo"
      /// }  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ConnectExReply ConnectEx(global::mt4_term_api.ConnectExRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectEx(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck",
      ///   "mtClusterName": "FreshForex-Demo"
      /// }  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ConnectExReply ConnectEx(global::mt4_term_api.ConnectExRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConnectEx, null, options, request);
      }
      /// <summary>
      /// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck",
      ///   "mtClusterName": "FreshForex-Demo"
      /// }  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ConnectExReply> ConnectExAsync(global::mt4_term_api.ConnectExRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectExAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck",
      ///   "mtClusterName": "FreshForex-Demo"
      /// }  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ConnectExReply> ConnectExAsync(global::mt4_term_api.ConnectExRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConnectEx, null, options, request);
      }
      /// <summary>
      /// Creates terminal connection to the MT4 server and returns Guid of it
      /// [DefaultValues]
      /// {
      ///   "user": "501401178",
      ///   "password": "v8gctta",
      ///   "host": "mt4-demo.roboforex.com",
      ///   "port": "443",
      ///   "baseChartSymbol": "EURUSD",  
      ///   "waitForTerminalIsAlive": "true"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ConnectReply Connect(global::mt4_term_api.ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates terminal connection to the MT4 server and returns Guid of it
      /// [DefaultValues]
      /// {
      ///   "user": "501401178",
      ///   "password": "v8gctta",
      ///   "host": "mt4-demo.roboforex.com",
      ///   "port": "443",
      ///   "baseChartSymbol": "EURUSD",  
      ///   "waitForTerminalIsAlive": "true"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ConnectReply Connect(global::mt4_term_api.ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Connect, null, options, request);
      }
      /// <summary>
      /// Creates terminal connection to the MT4 server and returns Guid of it
      /// [DefaultValues]
      /// {
      ///   "user": "501401178",
      ///   "password": "v8gctta",
      ///   "host": "mt4-demo.roboforex.com",
      ///   "port": "443",
      ///   "baseChartSymbol": "EURUSD",  
      ///   "waitForTerminalIsAlive": "true"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ConnectReply> ConnectAsync(global::mt4_term_api.ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates terminal connection to the MT4 server and returns Guid of it
      /// [DefaultValues]
      /// {
      ///   "user": "501401178",
      ///   "password": "v8gctta",
      ///   "host": "mt4-demo.roboforex.com",
      ///   "port": "443",
      ///   "baseChartSymbol": "EURUSD",  
      ///   "waitForTerminalIsAlive": "true"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ConnectReply> ConnectAsync(global::mt4_term_api.ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Connect, null, options, request);
      }
      /// <summary>
      /// Connect to account with user, password, host, port.
      /// [DefaultValues] 
      /// { 
      ///  "user": "500476959", 
      ///  "password": "ehj4bod", 
      ///  "host": "mt4-demo.roboforex.com", 
      ///  "port": "443",
      ///  "proxyUser": "ProxyUser123", 
      ///  "proxyPassword": "qwerty123", 
      ///  "proxyHost": "65.108.126.217", 
      ///  "proxyPort": "1080", 
      ///  "proxyType": "Socks5" 
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ConnectProxyReply ConnectProxy(global::mt4_term_api.ConnectProxyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectProxy(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Connect to account with user, password, host, port.
      /// [DefaultValues] 
      /// { 
      ///  "user": "500476959", 
      ///  "password": "ehj4bod", 
      ///  "host": "mt4-demo.roboforex.com", 
      ///  "port": "443",
      ///  "proxyUser": "ProxyUser123", 
      ///  "proxyPassword": "qwerty123", 
      ///  "proxyHost": "65.108.126.217", 
      ///  "proxyPort": "1080", 
      ///  "proxyType": "Socks5" 
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ConnectProxyReply ConnectProxy(global::mt4_term_api.ConnectProxyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConnectProxy, null, options, request);
      }
      /// <summary>
      /// Connect to account with user, password, host, port.
      /// [DefaultValues] 
      /// { 
      ///  "user": "500476959", 
      ///  "password": "ehj4bod", 
      ///  "host": "mt4-demo.roboforex.com", 
      ///  "port": "443",
      ///  "proxyUser": "ProxyUser123", 
      ///  "proxyPassword": "qwerty123", 
      ///  "proxyHost": "65.108.126.217", 
      ///  "proxyPort": "1080", 
      ///  "proxyType": "Socks5" 
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ConnectProxyReply> ConnectProxyAsync(global::mt4_term_api.ConnectProxyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectProxyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Connect to account with user, password, host, port.
      /// [DefaultValues] 
      /// { 
      ///  "user": "500476959", 
      ///  "password": "ehj4bod", 
      ///  "host": "mt4-demo.roboforex.com", 
      ///  "port": "443",
      ///  "proxyUser": "ProxyUser123", 
      ///  "proxyPassword": "qwerty123", 
      ///  "proxyHost": "65.108.126.217", 
      ///  "proxyPort": "1080", 
      ///  "proxyType": "Socks5" 
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ConnectProxyReply> ConnectProxyAsync(global::mt4_term_api.ConnectProxyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConnectProxy, null, options, request);
      }
      /// <summary>
      /// Checks if terminal connection to MT4 server is alive
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CheckConnectReply CheckConnect(global::mt4_term_api.CheckConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckConnect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Checks if terminal connection to MT4 server is alive
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CheckConnectReply CheckConnect(global::mt4_term_api.CheckConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckConnect, null, options, request);
      }
      /// <summary>
      /// Checks if terminal connection to MT4 server is alive
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CheckConnectReply> CheckConnectAsync(global::mt4_term_api.CheckConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Checks if terminal connection to MT4 server is alive
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CheckConnectReply> CheckConnectAsync(global::mt4_term_api.CheckConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckConnect, null, options, request);
      }
      /// <summary>
      /// Close terminal connection to MT4 server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.DisconnectReply Disconnect(global::mt4_term_api.DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Disconnect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Close terminal connection to MT4 server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.DisconnectReply Disconnect(global::mt4_term_api.DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Disconnect, null, options, request);
      }
      /// <summary>
      /// Close terminal connection to MT4 server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.DisconnectReply> DisconnectAsync(global::mt4_term_api.DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DisconnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Close terminal connection to MT4 server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.DisconnectReply> DisconnectAsync(global::mt4_term_api.DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Disconnect, null, options, request);
      }
      /// <summary>
      /// If you need to recreate terminal instance with the same id
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ReconnectReply Reconnect(global::mt4_term_api.ReconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Reconnect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// If you need to recreate terminal instance with the same id
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ReconnectReply Reconnect(global::mt4_term_api.ReconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Reconnect, null, options, request);
      }
      /// <summary>
      /// If you need to recreate terminal instance with the same id
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ReconnectReply> ReconnectAsync(global::mt4_term_api.ReconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReconnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// If you need to recreate terminal instance with the same id
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ReconnectReply> ReconnectAsync(global::mt4_term_api.ReconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Reconnect, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.GetBrokerServersByBrokerNameReply GetBrokerServersByBrokerName(global::mt4_term_api.GetBrokerServersByBrokerNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBrokerServersByBrokerName(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.GetBrokerServersByBrokerNameReply GetBrokerServersByBrokerName(global::mt4_term_api.GetBrokerServersByBrokerNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetBrokerServersByBrokerName, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.GetBrokerServersByBrokerNameReply> GetBrokerServersByBrokerNameAsync(global::mt4_term_api.GetBrokerServersByBrokerNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBrokerServersByBrokerNameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.GetBrokerServersByBrokerNameReply> GetBrokerServersByBrokerNameAsync(global::mt4_term_api.GetBrokerServersByBrokerNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetBrokerServersByBrokerName, null, options, request);
      }
      /// <summary>
      /// Generates a deterministic GUID from user and password.
      /// The same user/password combination always produces the same GUID.
      /// Use this GUID as the 'id' header for Connect and other endpoints.
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.GetIdReply GetId(global::mt4_term_api.GetIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a deterministic GUID from user and password.
      /// The same user/password combination always produces the same GUID.
      /// Use this GUID as the 'id' header for Connect and other endpoints.
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.GetIdReply GetId(global::mt4_term_api.GetIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetId, null, options, request);
      }
      /// <summary>
      /// Generates a deterministic GUID from user and password.
      /// The same user/password combination always produces the same GUID.
      /// Use this GUID as the 'id' header for Connect and other endpoints.
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.GetIdReply> GetIdAsync(global::mt4_term_api.GetIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a deterministic GUID from user and password.
      /// The same user/password combination always produces the same GUID.
      /// Use this GUID as the 'id' header for Connect and other endpoints.
      /// [DefaultValues]
      /// {
      ///   "user": "1124213727",
      ///   "password": "1tjvjck"
      /// }
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.GetIdReply> GetIdAsync(global::mt4_term_api.GetIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetId, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ConnectionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ConnectionClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ConnectionBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ConnectEx, serviceImpl.ConnectEx)
          .AddMethod(__Method_Connect, serviceImpl.Connect)
          .AddMethod(__Method_ConnectProxy, serviceImpl.ConnectProxy)
          .AddMethod(__Method_CheckConnect, serviceImpl.CheckConnect)
          .AddMethod(__Method_Disconnect, serviceImpl.Disconnect)
          .AddMethod(__Method_Reconnect, serviceImpl.Reconnect)
          .AddMethod(__Method_GetBrokerServersByBrokerName, serviceImpl.GetBrokerServersByBrokerName)
          .AddMethod(__Method_GetId, serviceImpl.GetId).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ConnectionBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ConnectEx, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.ConnectExRequest, global::mt4_term_api.ConnectExReply>(serviceImpl.ConnectEx));
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.ConnectRequest, global::mt4_term_api.ConnectReply>(serviceImpl.Connect));
      serviceBinder.AddMethod(__Method_ConnectProxy, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.ConnectProxyRequest, global::mt4_term_api.ConnectProxyReply>(serviceImpl.ConnectProxy));
      serviceBinder.AddMethod(__Method_CheckConnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.CheckConnectRequest, global::mt4_term_api.CheckConnectReply>(serviceImpl.CheckConnect));
      serviceBinder.AddMethod(__Method_Disconnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.DisconnectRequest, global::mt4_term_api.DisconnectReply>(serviceImpl.Disconnect));
      serviceBinder.AddMethod(__Method_Reconnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.ReconnectRequest, global::mt4_term_api.ReconnectReply>(serviceImpl.Reconnect));
      serviceBinder.AddMethod(__Method_GetBrokerServersByBrokerName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.GetBrokerServersByBrokerNameRequest, global::mt4_term_api.GetBrokerServersByBrokerNameReply>(serviceImpl.GetBrokerServersByBrokerName));
      serviceBinder.AddMethod(__Method_GetId, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.GetIdRequest, global::mt4_term_api.GetIdReply>(serviceImpl.GetId));
    }

  }
}
#endregion
