// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt4-term-api-internal-charts.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt4_term_api {
  public static partial class InternalCharts
  {
    static readonly string __ServiceName = "mt4_term_api.InternalCharts";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ChartOpenRequest> __Marshaller_mt4_term_api_ChartOpenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ChartOpenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ChartOpenReply> __Marshaller_mt4_term_api_ChartOpenReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ChartOpenReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ChartCloseRequest> __Marshaller_mt4_term_api_ChartCloseRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ChartCloseRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.ChartCloseReply> __Marshaller_mt4_term_api_ChartCloseReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.ChartCloseReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CustomChartOpenRequest> __Marshaller_mt4_term_api_CustomChartOpenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CustomChartOpenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CustomChartOpenReply> __Marshaller_mt4_term_api_CustomChartOpenReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CustomChartOpenReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CustomChartSaveTemplateRequest> __Marshaller_mt4_term_api_CustomChartSaveTemplateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CustomChartSaveTemplateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CustomChartSaveTemplateReply> __Marshaller_mt4_term_api_CustomChartSaveTemplateReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CustomChartSaveTemplateReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CustomChartApplyTemplateRequest> __Marshaller_mt4_term_api_CustomChartApplyTemplateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CustomChartApplyTemplateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.CustomChartApplyTemplateReply> __Marshaller_mt4_term_api_CustomChartApplyTemplateReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.CustomChartApplyTemplateReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.ChartOpenRequest, global::mt4_term_api.ChartOpenReply> __Method_ChartOpen = new grpc::Method<global::mt4_term_api.ChartOpenRequest, global::mt4_term_api.ChartOpenReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ChartOpen",
        __Marshaller_mt4_term_api_ChartOpenRequest,
        __Marshaller_mt4_term_api_ChartOpenReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.ChartCloseRequest, global::mt4_term_api.ChartCloseReply> __Method_ChartClose = new grpc::Method<global::mt4_term_api.ChartCloseRequest, global::mt4_term_api.ChartCloseReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ChartClose",
        __Marshaller_mt4_term_api_ChartCloseRequest,
        __Marshaller_mt4_term_api_ChartCloseReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.CustomChartOpenRequest, global::mt4_term_api.CustomChartOpenReply> __Method_CustomChartOpen = new grpc::Method<global::mt4_term_api.CustomChartOpenRequest, global::mt4_term_api.CustomChartOpenReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CustomChartOpen",
        __Marshaller_mt4_term_api_CustomChartOpenRequest,
        __Marshaller_mt4_term_api_CustomChartOpenReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.CustomChartSaveTemplateRequest, global::mt4_term_api.CustomChartSaveTemplateReply> __Method_CustomChartSaveTemplate = new grpc::Method<global::mt4_term_api.CustomChartSaveTemplateRequest, global::mt4_term_api.CustomChartSaveTemplateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CustomChartSaveTemplate",
        __Marshaller_mt4_term_api_CustomChartSaveTemplateRequest,
        __Marshaller_mt4_term_api_CustomChartSaveTemplateReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.CustomChartApplyTemplateRequest, global::mt4_term_api.CustomChartApplyTemplateReply> __Method_CustomChartApplyTemplate = new grpc::Method<global::mt4_term_api.CustomChartApplyTemplateRequest, global::mt4_term_api.CustomChartApplyTemplateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CustomChartApplyTemplate",
        __Marshaller_mt4_term_api_CustomChartApplyTemplateRequest,
        __Marshaller_mt4_term_api_CustomChartApplyTemplateReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt4_term_api.Mt4TermApiInternalChartsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InternalCharts</summary>
    [grpc::BindServiceMethod(typeof(InternalCharts), "BindService")]
    public abstract partial class InternalChartsBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.ChartOpenReply> ChartOpen(global::mt4_term_api.ChartOpenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.ChartCloseReply> ChartClose(global::mt4_term_api.ChartCloseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.CustomChartOpenReply> CustomChartOpen(global::mt4_term_api.CustomChartOpenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.CustomChartSaveTemplateReply> CustomChartSaveTemplate(global::mt4_term_api.CustomChartSaveTemplateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.CustomChartApplyTemplateReply> CustomChartApplyTemplate(global::mt4_term_api.CustomChartApplyTemplateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InternalCharts</summary>
    public partial class InternalChartsClient : grpc::ClientBase<InternalChartsClient>
    {
      /// <summary>Creates a new client for InternalCharts</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public InternalChartsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InternalCharts that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public InternalChartsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected InternalChartsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected InternalChartsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ChartOpenReply ChartOpen(global::mt4_term_api.ChartOpenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChartOpen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ChartOpenReply ChartOpen(global::mt4_term_api.ChartOpenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ChartOpen, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ChartOpenReply> ChartOpenAsync(global::mt4_term_api.ChartOpenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChartOpenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ChartOpenReply> ChartOpenAsync(global::mt4_term_api.ChartOpenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ChartOpen, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ChartCloseReply ChartClose(global::mt4_term_api.ChartCloseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChartClose(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.ChartCloseReply ChartClose(global::mt4_term_api.ChartCloseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ChartClose, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ChartCloseReply> ChartCloseAsync(global::mt4_term_api.ChartCloseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChartCloseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.ChartCloseReply> ChartCloseAsync(global::mt4_term_api.ChartCloseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ChartClose, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CustomChartOpenReply CustomChartOpen(global::mt4_term_api.CustomChartOpenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CustomChartOpen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CustomChartOpenReply CustomChartOpen(global::mt4_term_api.CustomChartOpenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CustomChartOpen, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CustomChartOpenReply> CustomChartOpenAsync(global::mt4_term_api.CustomChartOpenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CustomChartOpenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CustomChartOpenReply> CustomChartOpenAsync(global::mt4_term_api.CustomChartOpenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CustomChartOpen, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CustomChartSaveTemplateReply CustomChartSaveTemplate(global::mt4_term_api.CustomChartSaveTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CustomChartSaveTemplate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CustomChartSaveTemplateReply CustomChartSaveTemplate(global::mt4_term_api.CustomChartSaveTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CustomChartSaveTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CustomChartSaveTemplateReply> CustomChartSaveTemplateAsync(global::mt4_term_api.CustomChartSaveTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CustomChartSaveTemplateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CustomChartSaveTemplateReply> CustomChartSaveTemplateAsync(global::mt4_term_api.CustomChartSaveTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CustomChartSaveTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CustomChartApplyTemplateReply CustomChartApplyTemplate(global::mt4_term_api.CustomChartApplyTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CustomChartApplyTemplate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.CustomChartApplyTemplateReply CustomChartApplyTemplate(global::mt4_term_api.CustomChartApplyTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CustomChartApplyTemplate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CustomChartApplyTemplateReply> CustomChartApplyTemplateAsync(global::mt4_term_api.CustomChartApplyTemplateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CustomChartApplyTemplateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.CustomChartApplyTemplateReply> CustomChartApplyTemplateAsync(global::mt4_term_api.CustomChartApplyTemplateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CustomChartApplyTemplate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override InternalChartsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InternalChartsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(InternalChartsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ChartOpen, serviceImpl.ChartOpen)
          .AddMethod(__Method_ChartClose, serviceImpl.ChartClose)
          .AddMethod(__Method_CustomChartOpen, serviceImpl.CustomChartOpen)
          .AddMethod(__Method_CustomChartSaveTemplate, serviceImpl.CustomChartSaveTemplate)
          .AddMethod(__Method_CustomChartApplyTemplate, serviceImpl.CustomChartApplyTemplate).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, InternalChartsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ChartOpen, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.ChartOpenRequest, global::mt4_term_api.ChartOpenReply>(serviceImpl.ChartOpen));
      serviceBinder.AddMethod(__Method_ChartClose, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.ChartCloseRequest, global::mt4_term_api.ChartCloseReply>(serviceImpl.ChartClose));
      serviceBinder.AddMethod(__Method_CustomChartOpen, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.CustomChartOpenRequest, global::mt4_term_api.CustomChartOpenReply>(serviceImpl.CustomChartOpen));
      serviceBinder.AddMethod(__Method_CustomChartSaveTemplate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.CustomChartSaveTemplateRequest, global::mt4_term_api.CustomChartSaveTemplateReply>(serviceImpl.CustomChartSaveTemplate));
      serviceBinder.AddMethod(__Method_CustomChartApplyTemplate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.CustomChartApplyTemplateRequest, global::mt4_term_api.CustomChartApplyTemplateReply>(serviceImpl.CustomChartApplyTemplate));
    }

  }
}
#endregion
