// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt4-term-api-account-helper.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt4_term_api {
  public static partial class AccountHelper
  {
    static readonly string __ServiceName = "mt4_term_api.AccountHelper";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.AccountSummaryRequest> __Marshaller_mt4_term_api_AccountSummaryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.AccountSummaryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.AccountSummaryReply> __Marshaller_mt4_term_api_AccountSummaryReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.AccountSummaryReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.OpenedOrdersRequest> __Marshaller_mt4_term_api_OpenedOrdersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.OpenedOrdersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.OpenedOrdersReply> __Marshaller_mt4_term_api_OpenedOrdersReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.OpenedOrdersReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.OpenedOrdersTicketsRequest> __Marshaller_mt4_term_api_OpenedOrdersTicketsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.OpenedOrdersTicketsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.OpenedOrdersTicketsReply> __Marshaller_mt4_term_api_OpenedOrdersTicketsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.OpenedOrdersTicketsReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.OrdersHistoryRequest> __Marshaller_mt4_term_api_OrdersHistoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.OrdersHistoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.OrdersHistoryReply> __Marshaller_mt4_term_api_OrdersHistoryReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.OrdersHistoryReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.SymbolParamsManyRequest> __Marshaller_mt4_term_api_SymbolParamsManyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.SymbolParamsManyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.SymbolParamsManyReply> __Marshaller_mt4_term_api_SymbolParamsManyReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.SymbolParamsManyReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.TickValueWithSizeRequest> __Marshaller_mt4_term_api_TickValueWithSizeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.TickValueWithSizeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.TickValueWithSizeReply> __Marshaller_mt4_term_api_TickValueWithSizeReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.TickValueWithSizeReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.AccountSummaryRequest, global::mt4_term_api.AccountSummaryReply> __Method_AccountSummary = new grpc::Method<global::mt4_term_api.AccountSummaryRequest, global::mt4_term_api.AccountSummaryReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AccountSummary",
        __Marshaller_mt4_term_api_AccountSummaryRequest,
        __Marshaller_mt4_term_api_AccountSummaryReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.OpenedOrdersRequest, global::mt4_term_api.OpenedOrdersReply> __Method_OpenedOrders = new grpc::Method<global::mt4_term_api.OpenedOrdersRequest, global::mt4_term_api.OpenedOrdersReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OpenedOrders",
        __Marshaller_mt4_term_api_OpenedOrdersRequest,
        __Marshaller_mt4_term_api_OpenedOrdersReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.OpenedOrdersTicketsRequest, global::mt4_term_api.OpenedOrdersTicketsReply> __Method_OpenedOrdersTickets = new grpc::Method<global::mt4_term_api.OpenedOrdersTicketsRequest, global::mt4_term_api.OpenedOrdersTicketsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OpenedOrdersTickets",
        __Marshaller_mt4_term_api_OpenedOrdersTicketsRequest,
        __Marshaller_mt4_term_api_OpenedOrdersTicketsReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.OrdersHistoryRequest, global::mt4_term_api.OrdersHistoryReply> __Method_OrdersHistory = new grpc::Method<global::mt4_term_api.OrdersHistoryRequest, global::mt4_term_api.OrdersHistoryReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "OrdersHistory",
        __Marshaller_mt4_term_api_OrdersHistoryRequest,
        __Marshaller_mt4_term_api_OrdersHistoryReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.SymbolParamsManyRequest, global::mt4_term_api.SymbolParamsManyReply> __Method_SymbolParamsMany = new grpc::Method<global::mt4_term_api.SymbolParamsManyRequest, global::mt4_term_api.SymbolParamsManyReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SymbolParamsMany",
        __Marshaller_mt4_term_api_SymbolParamsManyRequest,
        __Marshaller_mt4_term_api_SymbolParamsManyReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.TickValueWithSizeRequest, global::mt4_term_api.TickValueWithSizeReply> __Method_TickValueWithSize = new grpc::Method<global::mt4_term_api.TickValueWithSizeRequest, global::mt4_term_api.TickValueWithSizeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TickValueWithSize",
        __Marshaller_mt4_term_api_TickValueWithSizeRequest,
        __Marshaller_mt4_term_api_TickValueWithSizeReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt4_term_api.Mt4TermApiAccountHelperReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AccountHelper</summary>
    [grpc::BindServiceMethod(typeof(AccountHelper), "BindService")]
    public abstract partial class AccountHelperBase
    {
      /// <summary>
      /// Some information about account
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.AccountSummaryReply> AccountSummary(global::mt4_term_api.AccountSummaryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// List of opened orders
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.OpenedOrdersReply> OpenedOrders(global::mt4_term_api.OpenedOrdersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// List of opened orders tickets
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.OpenedOrdersTicketsReply> OpenedOrdersTickets(global::mt4_term_api.OpenedOrdersTicketsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Orders history with pagination and open date filters
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.OrdersHistoryReply> OrdersHistory(global::mt4_term_api.OrdersHistoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Full information about exact symbol, or all symbols
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.SymbolParamsManyReply> SymbolParamsMany(global::mt4_term_api.SymbolParamsManyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.TickValueWithSizeReply> TickValueWithSize(global::mt4_term_api.TickValueWithSizeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AccountHelper</summary>
    public partial class AccountHelperClient : grpc::ClientBase<AccountHelperClient>
    {
      /// <summary>Creates a new client for AccountHelper</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AccountHelperClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AccountHelper that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AccountHelperClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AccountHelperClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AccountHelperClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Some information about account
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.AccountSummaryReply AccountSummary(global::mt4_term_api.AccountSummaryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AccountSummary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Some information about account
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.AccountSummaryReply AccountSummary(global::mt4_term_api.AccountSummaryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AccountSummary, null, options, request);
      }
      /// <summary>
      /// Some information about account
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.AccountSummaryReply> AccountSummaryAsync(global::mt4_term_api.AccountSummaryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AccountSummaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Some information about account
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.AccountSummaryReply> AccountSummaryAsync(global::mt4_term_api.AccountSummaryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AccountSummary, null, options, request);
      }
      /// <summary>
      /// List of opened orders
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.OpenedOrdersReply OpenedOrders(global::mt4_term_api.OpenedOrdersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenedOrders(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List of opened orders
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.OpenedOrdersReply OpenedOrders(global::mt4_term_api.OpenedOrdersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OpenedOrders, null, options, request);
      }
      /// <summary>
      /// List of opened orders
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.OpenedOrdersReply> OpenedOrdersAsync(global::mt4_term_api.OpenedOrdersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenedOrdersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List of opened orders
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.OpenedOrdersReply> OpenedOrdersAsync(global::mt4_term_api.OpenedOrdersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OpenedOrders, null, options, request);
      }
      /// <summary>
      /// List of opened orders tickets
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.OpenedOrdersTicketsReply OpenedOrdersTickets(global::mt4_term_api.OpenedOrdersTicketsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenedOrdersTickets(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List of opened orders tickets
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.OpenedOrdersTicketsReply OpenedOrdersTickets(global::mt4_term_api.OpenedOrdersTicketsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OpenedOrdersTickets, null, options, request);
      }
      /// <summary>
      /// List of opened orders tickets
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.OpenedOrdersTicketsReply> OpenedOrdersTicketsAsync(global::mt4_term_api.OpenedOrdersTicketsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenedOrdersTicketsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List of opened orders tickets
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.OpenedOrdersTicketsReply> OpenedOrdersTicketsAsync(global::mt4_term_api.OpenedOrdersTicketsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OpenedOrdersTickets, null, options, request);
      }
      /// <summary>
      /// Orders history with pagination and open date filters
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.OrdersHistoryReply OrdersHistory(global::mt4_term_api.OrdersHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OrdersHistory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Orders history with pagination and open date filters
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.OrdersHistoryReply OrdersHistory(global::mt4_term_api.OrdersHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OrdersHistory, null, options, request);
      }
      /// <summary>
      /// Orders history with pagination and open date filters
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.OrdersHistoryReply> OrdersHistoryAsync(global::mt4_term_api.OrdersHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OrdersHistoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Orders history with pagination and open date filters
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.OrdersHistoryReply> OrdersHistoryAsync(global::mt4_term_api.OrdersHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OrdersHistory, null, options, request);
      }
      /// <summary>
      /// Full information about exact symbol, or all symbols
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.SymbolParamsManyReply SymbolParamsMany(global::mt4_term_api.SymbolParamsManyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SymbolParamsMany(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Full information about exact symbol, or all symbols
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.SymbolParamsManyReply SymbolParamsMany(global::mt4_term_api.SymbolParamsManyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SymbolParamsMany, null, options, request);
      }
      /// <summary>
      /// Full information about exact symbol, or all symbols
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.SymbolParamsManyReply> SymbolParamsManyAsync(global::mt4_term_api.SymbolParamsManyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SymbolParamsManyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Full information about exact symbol, or all symbols
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.SymbolParamsManyReply> SymbolParamsManyAsync(global::mt4_term_api.SymbolParamsManyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SymbolParamsMany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.TickValueWithSizeReply TickValueWithSize(global::mt4_term_api.TickValueWithSizeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TickValueWithSize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.TickValueWithSizeReply TickValueWithSize(global::mt4_term_api.TickValueWithSizeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TickValueWithSize, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.TickValueWithSizeReply> TickValueWithSizeAsync(global::mt4_term_api.TickValueWithSizeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TickValueWithSizeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.TickValueWithSizeReply> TickValueWithSizeAsync(global::mt4_term_api.TickValueWithSizeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TickValueWithSize, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AccountHelperClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AccountHelperClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AccountHelperBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AccountSummary, serviceImpl.AccountSummary)
          .AddMethod(__Method_OpenedOrders, serviceImpl.OpenedOrders)
          .AddMethod(__Method_OpenedOrdersTickets, serviceImpl.OpenedOrdersTickets)
          .AddMethod(__Method_OrdersHistory, serviceImpl.OrdersHistory)
          .AddMethod(__Method_SymbolParamsMany, serviceImpl.SymbolParamsMany)
          .AddMethod(__Method_TickValueWithSize, serviceImpl.TickValueWithSize).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AccountHelperBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AccountSummary, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.AccountSummaryRequest, global::mt4_term_api.AccountSummaryReply>(serviceImpl.AccountSummary));
      serviceBinder.AddMethod(__Method_OpenedOrders, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.OpenedOrdersRequest, global::mt4_term_api.OpenedOrdersReply>(serviceImpl.OpenedOrders));
      serviceBinder.AddMethod(__Method_OpenedOrdersTickets, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.OpenedOrdersTicketsRequest, global::mt4_term_api.OpenedOrdersTicketsReply>(serviceImpl.OpenedOrdersTickets));
      serviceBinder.AddMethod(__Method_OrdersHistory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.OrdersHistoryRequest, global::mt4_term_api.OrdersHistoryReply>(serviceImpl.OrdersHistory));
      serviceBinder.AddMethod(__Method_SymbolParamsMany, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.SymbolParamsManyRequest, global::mt4_term_api.SymbolParamsManyReply>(serviceImpl.SymbolParamsMany));
      serviceBinder.AddMethod(__Method_TickValueWithSize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.TickValueWithSizeRequest, global::mt4_term_api.TickValueWithSizeReply>(serviceImpl.TickValueWithSize));
    }

  }
}
#endregion
