// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt4-term-api-market-info.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace mt4_term_api {
  public static partial class MarketInfo
  {
    static readonly string __ServiceName = "mt4_term_api.MarketInfo";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.QuoteRequest> __Marshaller_mt4_term_api_QuoteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.QuoteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.QuoteReply> __Marshaller_mt4_term_api_QuoteReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.QuoteReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.QuoteManyRequest> __Marshaller_mt4_term_api_QuoteManyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.QuoteManyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.QuoteManyReply> __Marshaller_mt4_term_api_QuoteManyReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.QuoteManyReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.SymbolsRequest> __Marshaller_mt4_term_api_SymbolsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.SymbolsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.SymbolsReply> __Marshaller_mt4_term_api_SymbolsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.SymbolsReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.QuoteHistoryRequest> __Marshaller_mt4_term_api_QuoteHistoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.QuoteHistoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.QuoteHistoryReply> __Marshaller_mt4_term_api_QuoteHistoryReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.QuoteHistoryReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.SymbolSelectRequest> __Marshaller_mt4_term_api_SymbolSelectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.SymbolSelectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::mt4_term_api.SymbolSelectReply> __Marshaller_mt4_term_api_SymbolSelectReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::mt4_term_api.SymbolSelectReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.QuoteRequest, global::mt4_term_api.QuoteReply> __Method_Quote = new grpc::Method<global::mt4_term_api.QuoteRequest, global::mt4_term_api.QuoteReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Quote",
        __Marshaller_mt4_term_api_QuoteRequest,
        __Marshaller_mt4_term_api_QuoteReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.QuoteManyRequest, global::mt4_term_api.QuoteManyReply> __Method_QuoteMany = new grpc::Method<global::mt4_term_api.QuoteManyRequest, global::mt4_term_api.QuoteManyReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QuoteMany",
        __Marshaller_mt4_term_api_QuoteManyRequest,
        __Marshaller_mt4_term_api_QuoteManyReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.SymbolsRequest, global::mt4_term_api.SymbolsReply> __Method_Symbols = new grpc::Method<global::mt4_term_api.SymbolsRequest, global::mt4_term_api.SymbolsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Symbols",
        __Marshaller_mt4_term_api_SymbolsRequest,
        __Marshaller_mt4_term_api_SymbolsReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.QuoteHistoryRequest, global::mt4_term_api.QuoteHistoryReply> __Method_QuoteHistory = new grpc::Method<global::mt4_term_api.QuoteHistoryRequest, global::mt4_term_api.QuoteHistoryReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QuoteHistory",
        __Marshaller_mt4_term_api_QuoteHistoryRequest,
        __Marshaller_mt4_term_api_QuoteHistoryReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::mt4_term_api.SymbolSelectRequest, global::mt4_term_api.SymbolSelectReply> __Method_SymbolSelect = new grpc::Method<global::mt4_term_api.SymbolSelectRequest, global::mt4_term_api.SymbolSelectReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SymbolSelect",
        __Marshaller_mt4_term_api_SymbolSelectRequest,
        __Marshaller_mt4_term_api_SymbolSelectReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::mt4_term_api.Mt4TermApiMarketInfoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MarketInfo</summary>
    [grpc::BindServiceMethod(typeof(MarketInfo), "BindService")]
    public abstract partial class MarketInfoBase
    {
      /// <summary>
      /// Get quote
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.QuoteReply> Quote(global::mt4_term_api.QuoteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Latest quote for the specified symbol
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.QuoteManyReply> QuoteMany(global::mt4_term_api.QuoteManyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.SymbolsReply> Symbols(global::mt4_term_api.SymbolsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.QuoteHistoryReply> QuoteHistory(global::mt4_term_api.QuoteHistoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Selects a symbol in the Market Watch window or removes a symbol from the window
      /// https://docs.mql4.com/marketinformation/symbolselect
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::mt4_term_api.SymbolSelectReply> SymbolSelect(global::mt4_term_api.SymbolSelectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MarketInfo</summary>
    public partial class MarketInfoClient : grpc::ClientBase<MarketInfoClient>
    {
      /// <summary>Creates a new client for MarketInfo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MarketInfoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MarketInfo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MarketInfoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MarketInfoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MarketInfoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Get quote
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.QuoteReply Quote(global::mt4_term_api.QuoteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Quote(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get quote
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.QuoteReply Quote(global::mt4_term_api.QuoteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Quote, null, options, request);
      }
      /// <summary>
      /// Get quote
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.QuoteReply> QuoteAsync(global::mt4_term_api.QuoteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QuoteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get quote
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.QuoteReply> QuoteAsync(global::mt4_term_api.QuoteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Quote, null, options, request);
      }
      /// <summary>
      /// Latest quote for the specified symbol
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.QuoteManyReply QuoteMany(global::mt4_term_api.QuoteManyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QuoteMany(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Latest quote for the specified symbol
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.QuoteManyReply QuoteMany(global::mt4_term_api.QuoteManyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QuoteMany, null, options, request);
      }
      /// <summary>
      /// Latest quote for the specified symbol
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.QuoteManyReply> QuoteManyAsync(global::mt4_term_api.QuoteManyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QuoteManyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Latest quote for the specified symbol
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.QuoteManyReply> QuoteManyAsync(global::mt4_term_api.QuoteManyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QuoteMany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.SymbolsReply Symbols(global::mt4_term_api.SymbolsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Symbols(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.SymbolsReply Symbols(global::mt4_term_api.SymbolsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Symbols, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.SymbolsReply> SymbolsAsync(global::mt4_term_api.SymbolsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SymbolsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.SymbolsReply> SymbolsAsync(global::mt4_term_api.SymbolsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Symbols, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.QuoteHistoryReply QuoteHistory(global::mt4_term_api.QuoteHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QuoteHistory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.QuoteHistoryReply QuoteHistory(global::mt4_term_api.QuoteHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QuoteHistory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.QuoteHistoryReply> QuoteHistoryAsync(global::mt4_term_api.QuoteHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QuoteHistoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.QuoteHistoryReply> QuoteHistoryAsync(global::mt4_term_api.QuoteHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QuoteHistory, null, options, request);
      }
      /// <summary>
      /// Selects a symbol in the Market Watch window or removes a symbol from the window
      /// https://docs.mql4.com/marketinformation/symbolselect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.SymbolSelectReply SymbolSelect(global::mt4_term_api.SymbolSelectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SymbolSelect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Selects a symbol in the Market Watch window or removes a symbol from the window
      /// https://docs.mql4.com/marketinformation/symbolselect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::mt4_term_api.SymbolSelectReply SymbolSelect(global::mt4_term_api.SymbolSelectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SymbolSelect, null, options, request);
      }
      /// <summary>
      /// Selects a symbol in the Market Watch window or removes a symbol from the window
      /// https://docs.mql4.com/marketinformation/symbolselect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.SymbolSelectReply> SymbolSelectAsync(global::mt4_term_api.SymbolSelectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SymbolSelectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Selects a symbol in the Market Watch window or removes a symbol from the window
      /// https://docs.mql4.com/marketinformation/symbolselect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::mt4_term_api.SymbolSelectReply> SymbolSelectAsync(global::mt4_term_api.SymbolSelectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SymbolSelect, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MarketInfoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MarketInfoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MarketInfoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Quote, serviceImpl.Quote)
          .AddMethod(__Method_QuoteMany, serviceImpl.QuoteMany)
          .AddMethod(__Method_Symbols, serviceImpl.Symbols)
          .AddMethod(__Method_QuoteHistory, serviceImpl.QuoteHistory)
          .AddMethod(__Method_SymbolSelect, serviceImpl.SymbolSelect).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MarketInfoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Quote, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.QuoteRequest, global::mt4_term_api.QuoteReply>(serviceImpl.Quote));
      serviceBinder.AddMethod(__Method_QuoteMany, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.QuoteManyRequest, global::mt4_term_api.QuoteManyReply>(serviceImpl.QuoteMany));
      serviceBinder.AddMethod(__Method_Symbols, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.SymbolsRequest, global::mt4_term_api.SymbolsReply>(serviceImpl.Symbols));
      serviceBinder.AddMethod(__Method_QuoteHistory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.QuoteHistoryRequest, global::mt4_term_api.QuoteHistoryReply>(serviceImpl.QuoteHistory));
      serviceBinder.AddMethod(__Method_SymbolSelect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::mt4_term_api.SymbolSelectRequest, global::mt4_term_api.SymbolSelectReply>(serviceImpl.SymbolSelect));
    }

  }
}
#endregion
