// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt4-term-api-demo-account.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace mt4_term_api {

  /// <summary>Holder for reflection information generated from mt4-term-api-demo-account.proto</summary>
  public static partial class Mt4TermApiDemoAccountReflection {

    #region Descriptor
    /// <summary>File descriptor for mt4-term-api-demo-account.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Mt4TermApiDemoAccountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9tdDQtdGVybS1hcGktZGVtby1hY2NvdW50LnByb3RvEgxtdDRfdGVybV9h",
            "cGkaHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aFm10NC10ZXJtLWFw",
            "aS1ndWkucHJvdG8yiwIKC0RlbW9BY2NvdW50EnwKD09wZW5EZW1vQWNjb3Vu",
            "dBInLm10NF90ZXJtX2FwaS5HdWlEZW1vT3BlbkFjY291bnRSZXF1ZXN0GiUu",
            "bXQ0X3Rlcm1fYXBpLkd1aURlbW9PcGVuQWNjb3VudFJlcGx5IhmC0+STAhMS",
            "ES9EZW1vQWNjb3VudC9PcGVuEn4KGkRlbW9PcGVuQWNjb3VudEludGVyYWN0",
            "aXZlEi0ubXQ0X3Rlcm1fYXBpLkd1aURlbW9JbnRlcmFjdGl2ZUNsaWVudE1l",
            "c3NhZ2UaLS5tdDRfdGVybV9hcGkuR3VpRGVtb0ludGVyYWN0aXZlU2VydmVy",
            "TWVzc2FnZSgBMAFCQloxZ2l0Lm10YXBpLmlvL3Jvb3QvbXJwYy1wcm90by5n",
            "aXQvbXQ0L2xpYnJhcmllcy9nb6oCDG10NF90ZXJtX2FwaWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::mt4_term_api.Mt4TermApiGuiReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
