// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mt4-term-api-charts.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace mt4_term_api {

  /// <summary>Holder for reflection information generated from mt4-term-api-charts.proto</summary>
  public static partial class Mt4TermApiChartsReflection {

    #region Descriptor
    /// <summary>File descriptor for mt4-term-api-charts.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Mt4TermApiChartsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChltdDQtdGVybS1hcGktY2hhcnRzLnByb3RvEgxtdDRfdGVybV9hcGkaHGdv",
            "b2dsZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aFG1ycGMtbXQ0LWVycm9yLnBy",
            "b3RvIioKEkdldEVhUGFyYW1zUmVxdWVzdBIUCgxlYV9maWxlX25hbWUYASAB",
            "KAkicwoQR2V0RWFQYXJhbXNSZXBseRItCgRkYXRhGAEgASgLMh0ubXQ0X3Rl",
            "cm1fYXBpLkdldEVhUGFyYW1zRGF0YUgAEiQKBWVycm9yGAIgASgLMhMubXQ0",
            "X3Rlcm1fYXBpLkVycm9ySABCCgoIcmVzcG9uc2UidgoPR2V0RWFQYXJhbXNE",
            "YXRhEg8KB2VhX25hbWUYASABKAkSEAoIZWFfZm91bmQYAiABKAgSFQoNZWFf",
            "aGFzX3BhcmFtcxgDIAEoCBIpCgpwYXJhbWV0ZXJzGAQgAygLMhUubXQ0X3Rl",
            "cm1fYXBpLkVhUGFyYW0iQgoHRWFQYXJhbRIMCgRuYW1lGAEgASgJEikKBHR5",
            "cGUYAiABKA4yGy5tdDRfdGVybV9hcGkuRUFfUEFSQU1fVFlQRSLdAQoeT3Bl",
            "blRlcm1pbmFsQ2hhcnRXaXRoRWFSZXF1ZXN0EhMKC3N5bWJvbF9uYW1lGAEg",
            "ASgJEhQKDGVhX2ZpbGVfbmFtZRgCIAEoCRJJCgxjaGFydF9wZXJpb2QYAyAB",
            "KA4yMy5tdDRfdGVybV9hcGkuRW51bU9wZW5UZXJtaW5hbENoYXJ0V2l0aEVh",
            "Q2hhdFBlcmlvZBJFCg1lYV9wYXJhbWV0ZXJzGAQgAygLMi4ubXQ0X3Rlcm1f",
            "YXBpLk9wZW5UZXJtaW5hbENoYXJ0V2l0aEVhUGFyYW1ldGVyIo8DCiBPcGVu",
            "VGVybWluYWxDaGFydFdpdGhFYVBhcmFtZXRlchINCgVpbmRleBgBIAEoBRJE",
            "CgR0eXBlGAIgASgOMjYubXQ0X3Rlcm1fYXBpLkVudW1PcGVuVGVybWluYWxD",
            "aGFydFdpdGhFYVBhcmFtZXRlclR5cGUSHAoPaW50X3BhcmFtX3ZhbHVlGAMg",
            "ASgFSACIAQESHQoQbG9uZ19wYXJhbV92YWx1ZRgEIAEoA0gBiAEBEh0KEGJv",
            "b2xfcGFyYW1fdmFsdWUYBSABKAhIAogBARIfChJzdHJpbmdfcGFyYW1fdmFs",
            "dWUYBiABKAlIA4gBARIfChJkb3VibGVfcGFyYW1fdmFsdWUYByABKAFIBIgB",
            "ARIMCgRuYW1lGAggASgJQhIKEF9pbnRfcGFyYW1fdmFsdWVCEwoRX2xvbmdf",
            "cGFyYW1fdmFsdWVCEwoRX2Jvb2xfcGFyYW1fdmFsdWVCFQoTX3N0cmluZ19w",
            "YXJhbV92YWx1ZUIVChNfZG91YmxlX3BhcmFtX3ZhbHVlIosBChxPcGVuVGVy",
            "bWluYWxDaGFydFdpdGhFYVJlcGx5EjkKBGRhdGEYASABKAsyKS5tdDRfdGVy",
            "bV9hcGkuT3BlblRlcm1pbmFsQ2hhcnRXaXRoRWFEYXRhSAASJAoFZXJyb3IY",
            "AiABKAsyEy5tdDRfdGVybV9hcGkuRXJyb3JIAEIKCghyZXNwb25zZSIvChtP",
            "cGVuVGVybWluYWxDaGFydFdpdGhFYURhdGESEAoIY2hhcnRfaWQYASABKAMq",
            "lgEKDUVBX1BBUkFNX1RZUEUSGwoXRUFfUEFSQU1fVFlQRV9VTkRFRklORUQQ",
            "ABIYChRFQV9QQVJBTV9UWVBFX1NUUklORxABEhkKFUVBX1BBUkFNX1RZUEVf",
            "SU5URUdFUhACEhgKFEVBX1BBUkFNX1RZUEVfRE9VQkxFEAMSGQoVRUFfUEFS",
            "QU1fVFlQRV9CT09MRUFOEAQqpQEKKEVudW1PcGVuVGVybWluYWxDaGFydFdp",
            "dGhFYVBhcmFtZXRlclR5cGUSFQoRTVJQQ19FQV9QQVJBTV9JTlQQABIWChJN",
            "UlBDX0VBX1BBUkFNX0xPTkcQARIWChJNUlBDX0VBX1BBUkFNX0JPT0wQAhIY",
            "ChRNUlBDX0VBX1BBUkFNX1NUUklORxADEhgKFE1SUENfRUFfUEFSQU1fRE9V",
            "QkxFEAQqsQUKJUVudW1PcGVuVGVybWluYWxDaGFydFdpdGhFYUNoYXRQZXJp",
            "b2QSIAocTVJQQ19FQV9DSEFSVF9QRVJJT0RfQ1VSUkVOVBAAEhsKF01SUENf",
            "RUFfQ0hBUlRfUEVSSU9EX00xEAESGwoXTVJQQ19FQV9DSEFSVF9QRVJJT0Rf",
            "TTIQAhIbChdNUlBDX0VBX0NIQVJUX1BFUklPRF9NMxADEhsKF01SUENfRUFf",
            "Q0hBUlRfUEVSSU9EX000EAQSGwoXTVJQQ19FQV9DSEFSVF9QRVJJT0RfTTUQ",
            "BRIbChdNUlBDX0VBX0NIQVJUX1BFUklPRF9NNhAGEhwKGE1SUENfRUFfQ0hB",
            "UlRfUEVSSU9EX00xMBAHEhwKGE1SUENfRUFfQ0hBUlRfUEVSSU9EX00xMhAI",
            "EhwKGE1SUENfRUFfQ0hBUlRfUEVSSU9EX00xNRAJEhwKGE1SUENfRUFfQ0hB",
            "UlRfUEVSSU9EX00yMBAKEhwKGE1SUENfRUFfQ0hBUlRfUEVSSU9EX00zMBAL",
            "EhsKF01SUENfRUFfQ0hBUlRfUEVSSU9EX0gxEAwSGwoXTVJQQ19FQV9DSEFS",
            "VF9QRVJJT0RfSDIQDRIbChdNUlBDX0VBX0NIQVJUX1BFUklPRF9IMxAOEhsK",
            "F01SUENfRUFfQ0hBUlRfUEVSSU9EX0g0EA8SGwoXTVJQQ19FQV9DSEFSVF9Q",
            "RVJJT0RfSDYQEBIbChdNUlBDX0VBX0NIQVJUX1BFUklPRF9IOBAREhwKGE1S",
            "UENfRUFfQ0hBUlRfUEVSSU9EX0gxMhASEhsKF01SUENfRUFfQ0hBUlRfUEVS",
            "SU9EX0QxEBMSGwoXTVJQQ19FQV9DSEFSVF9QRVJJT0RfVzEQFBIcChhNUlBD",
            "X0VBX0NIQVJUX1BFUklPRF9NTjEQFTKHAgoGQ2hhcnRzEmUKC0dldEVhUGFy",
            "YW1zEiAubXQ0X3Rlcm1fYXBpLkdldEVhUGFyYW1zUmVxdWVzdBoeLm10NF90",
            "ZXJtX2FwaS5HZXRFYVBhcmFtc1JlcGx5IhSC0+STAg4SDC9HZXRFYVBhcmFt",
            "cxKVAQoXT3BlblRlcm1pbmFsQ2hhcnRXaXRoRWESLC5tdDRfdGVybV9hcGku",
            "T3BlblRlcm1pbmFsQ2hhcnRXaXRoRWFSZXF1ZXN0GioubXQ0X3Rlcm1fYXBp",
            "Lk9wZW5UZXJtaW5hbENoYXJ0V2l0aEVhUmVwbHkiIILT5JMCGhIYL09wZW5U",
            "ZXJtaW5hbENoYXJ0V2l0aEVhQkJaMWdpdC5tdGFwaS5pby9yb290L21ycGMt",
            "cHJvdG8uZ2l0L210NC9saWJyYXJpZXMvZ2+qAgxtdDRfdGVybV9hcGliBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Mt4TermApi.MrpcMt4ErrorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::mt4_term_api.EA_PARAM_TYPE), typeof(global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType), typeof(global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.GetEaParamsRequest), global::mt4_term_api.GetEaParamsRequest.Parser, new[]{ "EaFileName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.GetEaParamsReply), global::mt4_term_api.GetEaParamsReply.Parser, new[]{ "Data", "Error" }, new[]{ "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.GetEaParamsData), global::mt4_term_api.GetEaParamsData.Parser, new[]{ "EaName", "EaFound", "EaHasParams", "Parameters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.EaParam), global::mt4_term_api.EaParam.Parser, new[]{ "Name", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.OpenTerminalChartWithEaRequest), global::mt4_term_api.OpenTerminalChartWithEaRequest.Parser, new[]{ "SymbolName", "EaFileName", "ChartPeriod", "EaParameters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.OpenTerminalChartWithEaParameter), global::mt4_term_api.OpenTerminalChartWithEaParameter.Parser, new[]{ "Index", "Type", "IntParamValue", "LongParamValue", "BoolParamValue", "StringParamValue", "DoubleParamValue", "Name" }, new[]{ "IntParamValue", "LongParamValue", "BoolParamValue", "StringParamValue", "DoubleParamValue" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.OpenTerminalChartWithEaReply), global::mt4_term_api.OpenTerminalChartWithEaReply.Parser, new[]{ "Data", "Error" }, new[]{ "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::mt4_term_api.OpenTerminalChartWithEaData), global::mt4_term_api.OpenTerminalChartWithEaData.Parser, new[]{ "ChartId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EA_PARAM_TYPE {
    [pbr::OriginalName("EA_PARAM_TYPE_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("EA_PARAM_TYPE_STRING")] String = 1,
    [pbr::OriginalName("EA_PARAM_TYPE_INTEGER")] Integer = 2,
    [pbr::OriginalName("EA_PARAM_TYPE_DOUBLE")] Double = 3,
    [pbr::OriginalName("EA_PARAM_TYPE_BOOLEAN")] Boolean = 4,
  }

  public enum EnumOpenTerminalChartWithEaParameterType {
    [pbr::OriginalName("MRPC_EA_PARAM_INT")] MrpcEaParamInt = 0,
    [pbr::OriginalName("MRPC_EA_PARAM_LONG")] MrpcEaParamLong = 1,
    [pbr::OriginalName("MRPC_EA_PARAM_BOOL")] MrpcEaParamBool = 2,
    [pbr::OriginalName("MRPC_EA_PARAM_STRING")] MrpcEaParamString = 3,
    [pbr::OriginalName("MRPC_EA_PARAM_DOUBLE")] MrpcEaParamDouble = 4,
  }

  public enum EnumOpenTerminalChartWithEaChatPeriod {
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_CURRENT")] MrpcEaChartPeriodCurrent = 0,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M1")] MrpcEaChartPeriodM1 = 1,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M2")] MrpcEaChartPeriodM2 = 2,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M3")] MrpcEaChartPeriodM3 = 3,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M4")] MrpcEaChartPeriodM4 = 4,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M5")] MrpcEaChartPeriodM5 = 5,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M6")] MrpcEaChartPeriodM6 = 6,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M10")] MrpcEaChartPeriodM10 = 7,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M12")] MrpcEaChartPeriodM12 = 8,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M15")] MrpcEaChartPeriodM15 = 9,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M20")] MrpcEaChartPeriodM20 = 10,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_M30")] MrpcEaChartPeriodM30 = 11,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H1")] MrpcEaChartPeriodH1 = 12,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H2")] MrpcEaChartPeriodH2 = 13,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H3")] MrpcEaChartPeriodH3 = 14,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H4")] MrpcEaChartPeriodH4 = 15,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H6")] MrpcEaChartPeriodH6 = 16,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H8")] MrpcEaChartPeriodH8 = 17,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_H12")] MrpcEaChartPeriodH12 = 18,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_D1")] MrpcEaChartPeriodD1 = 19,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_W1")] MrpcEaChartPeriodW1 = 20,
    [pbr::OriginalName("MRPC_EA_CHART_PERIOD_MN1")] MrpcEaChartPeriodMn1 = 21,
  }

  #endregion

  #region Messages
  public sealed partial class GetEaParamsRequest : pb::IMessage<GetEaParamsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEaParamsRequest> _parser = new pb::MessageParser<GetEaParamsRequest>(() => new GetEaParamsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEaParamsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsRequest(GetEaParamsRequest other) : this() {
      eaFileName_ = other.eaFileName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsRequest Clone() {
      return new GetEaParamsRequest(this);
    }

    /// <summary>Field number for the "ea_file_name" field.</summary>
    public const int EaFileNameFieldNumber = 1;
    private string eaFileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EaFileName {
      get { return eaFileName_; }
      set {
        eaFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEaParamsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEaParamsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EaFileName != other.EaFileName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EaFileName.Length != 0) hash ^= EaFileName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EaFileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EaFileName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EaFileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EaFileName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EaFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EaFileName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEaParamsRequest other) {
      if (other == null) {
        return;
      }
      if (other.EaFileName.Length != 0) {
        EaFileName = other.EaFileName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EaFileName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EaFileName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetEaParamsReply : pb::IMessage<GetEaParamsReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEaParamsReply> _parser = new pb::MessageParser<GetEaParamsReply>(() => new GetEaParamsReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEaParamsReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsReply(GetEaParamsReply other) : this() {
      switch (other.ResponseCase) {
        case ResponseOneofCase.Data:
          Data = other.Data.Clone();
          break;
        case ResponseOneofCase.Error:
          Error = other.Error.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsReply Clone() {
      return new GetEaParamsReply(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::mt4_term_api.GetEaParamsData Data {
      get { return responseCase_ == ResponseOneofCase.Data ? (global::mt4_term_api.GetEaParamsData) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Data;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mt4TermApi.Error Error {
      get { return responseCase_ == ResponseOneofCase.Error ? (global::Mt4TermApi.Error) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Error;
      }
    }

    private object response_;
    /// <summary>Enum of possible cases for the "response" oneof.</summary>
    public enum ResponseOneofCase {
      None = 0,
      Data = 1,
      Error = 2,
    }
    private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseOneofCase ResponseCase {
      get { return responseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponse() {
      responseCase_ = ResponseOneofCase.None;
      response_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEaParamsReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEaParamsReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      if (!object.Equals(Error, other.Error)) return false;
      if (ResponseCase != other.ResponseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (responseCase_ == ResponseOneofCase.Data) hash ^= Data.GetHashCode();
      if (responseCase_ == ResponseOneofCase.Error) hash ^= Error.GetHashCode();
      hash ^= (int) responseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (responseCase_ == ResponseOneofCase.Data) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (responseCase_ == ResponseOneofCase.Data) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (responseCase_ == ResponseOneofCase.Data) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEaParamsReply other) {
      if (other == null) {
        return;
      }
      switch (other.ResponseCase) {
        case ResponseOneofCase.Data:
          if (Data == null) {
            Data = new global::mt4_term_api.GetEaParamsData();
          }
          Data.MergeFrom(other.Data);
          break;
        case ResponseOneofCase.Error:
          if (Error == null) {
            Error = new global::Mt4TermApi.Error();
          }
          Error.MergeFrom(other.Error);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::mt4_term_api.GetEaParamsData subBuilder = new global::mt4_term_api.GetEaParamsData();
            if (responseCase_ == ResponseOneofCase.Data) {
              subBuilder.MergeFrom(Data);
            }
            input.ReadMessage(subBuilder);
            Data = subBuilder;
            break;
          }
          case 18: {
            global::Mt4TermApi.Error subBuilder = new global::Mt4TermApi.Error();
            if (responseCase_ == ResponseOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::mt4_term_api.GetEaParamsData subBuilder = new global::mt4_term_api.GetEaParamsData();
            if (responseCase_ == ResponseOneofCase.Data) {
              subBuilder.MergeFrom(Data);
            }
            input.ReadMessage(subBuilder);
            Data = subBuilder;
            break;
          }
          case 18: {
            global::Mt4TermApi.Error subBuilder = new global::Mt4TermApi.Error();
            if (responseCase_ == ResponseOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetEaParamsData : pb::IMessage<GetEaParamsData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEaParamsData> _parser = new pb::MessageParser<GetEaParamsData>(() => new GetEaParamsData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEaParamsData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsData(GetEaParamsData other) : this() {
      eaName_ = other.eaName_;
      eaFound_ = other.eaFound_;
      eaHasParams_ = other.eaHasParams_;
      parameters_ = other.parameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEaParamsData Clone() {
      return new GetEaParamsData(this);
    }

    /// <summary>Field number for the "ea_name" field.</summary>
    public const int EaNameFieldNumber = 1;
    private string eaName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EaName {
      get { return eaName_; }
      set {
        eaName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ea_found" field.</summary>
    public const int EaFoundFieldNumber = 2;
    private bool eaFound_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EaFound {
      get { return eaFound_; }
      set {
        eaFound_ = value;
      }
    }

    /// <summary>Field number for the "ea_has_params" field.</summary>
    public const int EaHasParamsFieldNumber = 3;
    private bool eaHasParams_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EaHasParams {
      get { return eaHasParams_; }
      set {
        eaHasParams_ = value;
      }
    }

    /// <summary>Field number for the "parameters" field.</summary>
    public const int ParametersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::mt4_term_api.EaParam> _repeated_parameters_codec
        = pb::FieldCodec.ForMessage(34, global::mt4_term_api.EaParam.Parser);
    private readonly pbc::RepeatedField<global::mt4_term_api.EaParam> parameters_ = new pbc::RepeatedField<global::mt4_term_api.EaParam>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mt4_term_api.EaParam> Parameters {
      get { return parameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEaParamsData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEaParamsData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EaName != other.EaName) return false;
      if (EaFound != other.EaFound) return false;
      if (EaHasParams != other.EaHasParams) return false;
      if(!parameters_.Equals(other.parameters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EaName.Length != 0) hash ^= EaName.GetHashCode();
      if (EaFound != false) hash ^= EaFound.GetHashCode();
      if (EaHasParams != false) hash ^= EaHasParams.GetHashCode();
      hash ^= parameters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EaName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EaName);
      }
      if (EaFound != false) {
        output.WriteRawTag(16);
        output.WriteBool(EaFound);
      }
      if (EaHasParams != false) {
        output.WriteRawTag(24);
        output.WriteBool(EaHasParams);
      }
      parameters_.WriteTo(output, _repeated_parameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EaName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EaName);
      }
      if (EaFound != false) {
        output.WriteRawTag(16);
        output.WriteBool(EaFound);
      }
      if (EaHasParams != false) {
        output.WriteRawTag(24);
        output.WriteBool(EaHasParams);
      }
      parameters_.WriteTo(ref output, _repeated_parameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EaName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EaName);
      }
      if (EaFound != false) {
        size += 1 + 1;
      }
      if (EaHasParams != false) {
        size += 1 + 1;
      }
      size += parameters_.CalculateSize(_repeated_parameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEaParamsData other) {
      if (other == null) {
        return;
      }
      if (other.EaName.Length != 0) {
        EaName = other.EaName;
      }
      if (other.EaFound != false) {
        EaFound = other.EaFound;
      }
      if (other.EaHasParams != false) {
        EaHasParams = other.EaHasParams;
      }
      parameters_.Add(other.parameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EaName = input.ReadString();
            break;
          }
          case 16: {
            EaFound = input.ReadBool();
            break;
          }
          case 24: {
            EaHasParams = input.ReadBool();
            break;
          }
          case 34: {
            parameters_.AddEntriesFrom(input, _repeated_parameters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EaName = input.ReadString();
            break;
          }
          case 16: {
            EaFound = input.ReadBool();
            break;
          }
          case 24: {
            EaHasParams = input.ReadBool();
            break;
          }
          case 34: {
            parameters_.AddEntriesFrom(ref input, _repeated_parameters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EaParam : pb::IMessage<EaParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EaParam> _parser = new pb::MessageParser<EaParam>(() => new EaParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EaParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EaParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EaParam(EaParam other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EaParam Clone() {
      return new EaParam(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::mt4_term_api.EA_PARAM_TYPE type_ = global::mt4_term_api.EA_PARAM_TYPE.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::mt4_term_api.EA_PARAM_TYPE Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EaParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EaParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != global::mt4_term_api.EA_PARAM_TYPE.Undefined) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::mt4_term_api.EA_PARAM_TYPE.Undefined) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::mt4_term_api.EA_PARAM_TYPE.Undefined) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != global::mt4_term_api.EA_PARAM_TYPE.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EaParam other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != global::mt4_term_api.EA_PARAM_TYPE.Undefined) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::mt4_term_api.EA_PARAM_TYPE) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::mt4_term_api.EA_PARAM_TYPE) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OpenTerminalChartWithEaRequest : pb::IMessage<OpenTerminalChartWithEaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenTerminalChartWithEaRequest> _parser = new pb::MessageParser<OpenTerminalChartWithEaRequest>(() => new OpenTerminalChartWithEaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenTerminalChartWithEaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaRequest(OpenTerminalChartWithEaRequest other) : this() {
      symbolName_ = other.symbolName_;
      eaFileName_ = other.eaFileName_;
      chartPeriod_ = other.chartPeriod_;
      eaParameters_ = other.eaParameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaRequest Clone() {
      return new OpenTerminalChartWithEaRequest(this);
    }

    /// <summary>Field number for the "symbol_name" field.</summary>
    public const int SymbolNameFieldNumber = 1;
    private string symbolName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SymbolName {
      get { return symbolName_; }
      set {
        symbolName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ea_file_name" field.</summary>
    public const int EaFileNameFieldNumber = 2;
    private string eaFileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EaFileName {
      get { return eaFileName_; }
      set {
        eaFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chart_period" field.</summary>
    public const int ChartPeriodFieldNumber = 3;
    private global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod chartPeriod_ = global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod.MrpcEaChartPeriodCurrent;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod ChartPeriod {
      get { return chartPeriod_; }
      set {
        chartPeriod_ = value;
      }
    }

    /// <summary>Field number for the "ea_parameters" field.</summary>
    public const int EaParametersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::mt4_term_api.OpenTerminalChartWithEaParameter> _repeated_eaParameters_codec
        = pb::FieldCodec.ForMessage(34, global::mt4_term_api.OpenTerminalChartWithEaParameter.Parser);
    private readonly pbc::RepeatedField<global::mt4_term_api.OpenTerminalChartWithEaParameter> eaParameters_ = new pbc::RepeatedField<global::mt4_term_api.OpenTerminalChartWithEaParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::mt4_term_api.OpenTerminalChartWithEaParameter> EaParameters {
      get { return eaParameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenTerminalChartWithEaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenTerminalChartWithEaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SymbolName != other.SymbolName) return false;
      if (EaFileName != other.EaFileName) return false;
      if (ChartPeriod != other.ChartPeriod) return false;
      if(!eaParameters_.Equals(other.eaParameters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SymbolName.Length != 0) hash ^= SymbolName.GetHashCode();
      if (EaFileName.Length != 0) hash ^= EaFileName.GetHashCode();
      if (ChartPeriod != global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod.MrpcEaChartPeriodCurrent) hash ^= ChartPeriod.GetHashCode();
      hash ^= eaParameters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SymbolName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SymbolName);
      }
      if (EaFileName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EaFileName);
      }
      if (ChartPeriod != global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod.MrpcEaChartPeriodCurrent) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ChartPeriod);
      }
      eaParameters_.WriteTo(output, _repeated_eaParameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SymbolName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SymbolName);
      }
      if (EaFileName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EaFileName);
      }
      if (ChartPeriod != global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod.MrpcEaChartPeriodCurrent) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ChartPeriod);
      }
      eaParameters_.WriteTo(ref output, _repeated_eaParameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SymbolName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SymbolName);
      }
      if (EaFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EaFileName);
      }
      if (ChartPeriod != global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod.MrpcEaChartPeriodCurrent) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChartPeriod);
      }
      size += eaParameters_.CalculateSize(_repeated_eaParameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenTerminalChartWithEaRequest other) {
      if (other == null) {
        return;
      }
      if (other.SymbolName.Length != 0) {
        SymbolName = other.SymbolName;
      }
      if (other.EaFileName.Length != 0) {
        EaFileName = other.EaFileName;
      }
      if (other.ChartPeriod != global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod.MrpcEaChartPeriodCurrent) {
        ChartPeriod = other.ChartPeriod;
      }
      eaParameters_.Add(other.eaParameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SymbolName = input.ReadString();
            break;
          }
          case 18: {
            EaFileName = input.ReadString();
            break;
          }
          case 24: {
            ChartPeriod = (global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod) input.ReadEnum();
            break;
          }
          case 34: {
            eaParameters_.AddEntriesFrom(input, _repeated_eaParameters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SymbolName = input.ReadString();
            break;
          }
          case 18: {
            EaFileName = input.ReadString();
            break;
          }
          case 24: {
            ChartPeriod = (global::mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod) input.ReadEnum();
            break;
          }
          case 34: {
            eaParameters_.AddEntriesFrom(ref input, _repeated_eaParameters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OpenTerminalChartWithEaParameter : pb::IMessage<OpenTerminalChartWithEaParameter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenTerminalChartWithEaParameter> _parser = new pb::MessageParser<OpenTerminalChartWithEaParameter>(() => new OpenTerminalChartWithEaParameter());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenTerminalChartWithEaParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaParameter(OpenTerminalChartWithEaParameter other) : this() {
      _hasBits0 = other._hasBits0;
      index_ = other.index_;
      type_ = other.type_;
      intParamValue_ = other.intParamValue_;
      longParamValue_ = other.longParamValue_;
      boolParamValue_ = other.boolParamValue_;
      stringParamValue_ = other.stringParamValue_;
      doubleParamValue_ = other.doubleParamValue_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaParameter Clone() {
      return new OpenTerminalChartWithEaParameter(this);
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 1;
    private int index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType type_ = global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType.MrpcEaParamInt;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "int_param_value" field.</summary>
    public const int IntParamValueFieldNumber = 3;
    private int intParamValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IntParamValue {
      get { if ((_hasBits0 & 1) != 0) { return intParamValue_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        intParamValue_ = value;
      }
    }
    /// <summary>Gets whether the "int_param_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIntParamValue {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "int_param_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIntParamValue() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "long_param_value" field.</summary>
    public const int LongParamValueFieldNumber = 4;
    private long longParamValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LongParamValue {
      get { if ((_hasBits0 & 2) != 0) { return longParamValue_; } else { return 0L; } }
      set {
        _hasBits0 |= 2;
        longParamValue_ = value;
      }
    }
    /// <summary>Gets whether the "long_param_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLongParamValue {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "long_param_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLongParamValue() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "bool_param_value" field.</summary>
    public const int BoolParamValueFieldNumber = 5;
    private bool boolParamValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BoolParamValue {
      get { if ((_hasBits0 & 4) != 0) { return boolParamValue_; } else { return false; } }
      set {
        _hasBits0 |= 4;
        boolParamValue_ = value;
      }
    }
    /// <summary>Gets whether the "bool_param_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBoolParamValue {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "bool_param_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBoolParamValue() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "string_param_value" field.</summary>
    public const int StringParamValueFieldNumber = 6;
    private string stringParamValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringParamValue {
      get { return stringParamValue_ ?? ""; }
      set {
        stringParamValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "string_param_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringParamValue {
      get { return stringParamValue_ != null; }
    }
    /// <summary>Clears the value of the "string_param_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringParamValue() {
      stringParamValue_ = null;
    }

    /// <summary>Field number for the "double_param_value" field.</summary>
    public const int DoubleParamValueFieldNumber = 7;
    private double doubleParamValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DoubleParamValue {
      get { if ((_hasBits0 & 8) != 0) { return doubleParamValue_; } else { return 0D; } }
      set {
        _hasBits0 |= 8;
        doubleParamValue_ = value;
      }
    }
    /// <summary>Gets whether the "double_param_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDoubleParamValue {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "double_param_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDoubleParamValue() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 8;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenTerminalChartWithEaParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenTerminalChartWithEaParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Index != other.Index) return false;
      if (Type != other.Type) return false;
      if (IntParamValue != other.IntParamValue) return false;
      if (LongParamValue != other.LongParamValue) return false;
      if (BoolParamValue != other.BoolParamValue) return false;
      if (StringParamValue != other.StringParamValue) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleParamValue, other.DoubleParamValue)) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Index != 0) hash ^= Index.GetHashCode();
      if (Type != global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType.MrpcEaParamInt) hash ^= Type.GetHashCode();
      if (HasIntParamValue) hash ^= IntParamValue.GetHashCode();
      if (HasLongParamValue) hash ^= LongParamValue.GetHashCode();
      if (HasBoolParamValue) hash ^= BoolParamValue.GetHashCode();
      if (HasStringParamValue) hash ^= StringParamValue.GetHashCode();
      if (HasDoubleParamValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleParamValue);
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Index != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Index);
      }
      if (Type != global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType.MrpcEaParamInt) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (HasIntParamValue) {
        output.WriteRawTag(24);
        output.WriteInt32(IntParamValue);
      }
      if (HasLongParamValue) {
        output.WriteRawTag(32);
        output.WriteInt64(LongParamValue);
      }
      if (HasBoolParamValue) {
        output.WriteRawTag(40);
        output.WriteBool(BoolParamValue);
      }
      if (HasStringParamValue) {
        output.WriteRawTag(50);
        output.WriteString(StringParamValue);
      }
      if (HasDoubleParamValue) {
        output.WriteRawTag(57);
        output.WriteDouble(DoubleParamValue);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Index != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Index);
      }
      if (Type != global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType.MrpcEaParamInt) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (HasIntParamValue) {
        output.WriteRawTag(24);
        output.WriteInt32(IntParamValue);
      }
      if (HasLongParamValue) {
        output.WriteRawTag(32);
        output.WriteInt64(LongParamValue);
      }
      if (HasBoolParamValue) {
        output.WriteRawTag(40);
        output.WriteBool(BoolParamValue);
      }
      if (HasStringParamValue) {
        output.WriteRawTag(50);
        output.WriteString(StringParamValue);
      }
      if (HasDoubleParamValue) {
        output.WriteRawTag(57);
        output.WriteDouble(DoubleParamValue);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
      }
      if (Type != global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType.MrpcEaParamInt) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasIntParamValue) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntParamValue);
      }
      if (HasLongParamValue) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LongParamValue);
      }
      if (HasBoolParamValue) {
        size += 1 + 1;
      }
      if (HasStringParamValue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringParamValue);
      }
      if (HasDoubleParamValue) {
        size += 1 + 8;
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenTerminalChartWithEaParameter other) {
      if (other == null) {
        return;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      if (other.Type != global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType.MrpcEaParamInt) {
        Type = other.Type;
      }
      if (other.HasIntParamValue) {
        IntParamValue = other.IntParamValue;
      }
      if (other.HasLongParamValue) {
        LongParamValue = other.LongParamValue;
      }
      if (other.HasBoolParamValue) {
        BoolParamValue = other.BoolParamValue;
      }
      if (other.HasStringParamValue) {
        StringParamValue = other.StringParamValue;
      }
      if (other.HasDoubleParamValue) {
        DoubleParamValue = other.DoubleParamValue;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Index = input.ReadInt32();
            break;
          }
          case 16: {
            Type = (global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType) input.ReadEnum();
            break;
          }
          case 24: {
            IntParamValue = input.ReadInt32();
            break;
          }
          case 32: {
            LongParamValue = input.ReadInt64();
            break;
          }
          case 40: {
            BoolParamValue = input.ReadBool();
            break;
          }
          case 50: {
            StringParamValue = input.ReadString();
            break;
          }
          case 57: {
            DoubleParamValue = input.ReadDouble();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Index = input.ReadInt32();
            break;
          }
          case 16: {
            Type = (global::mt4_term_api.EnumOpenTerminalChartWithEaParameterType) input.ReadEnum();
            break;
          }
          case 24: {
            IntParamValue = input.ReadInt32();
            break;
          }
          case 32: {
            LongParamValue = input.ReadInt64();
            break;
          }
          case 40: {
            BoolParamValue = input.ReadBool();
            break;
          }
          case 50: {
            StringParamValue = input.ReadString();
            break;
          }
          case 57: {
            DoubleParamValue = input.ReadDouble();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OpenTerminalChartWithEaReply : pb::IMessage<OpenTerminalChartWithEaReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenTerminalChartWithEaReply> _parser = new pb::MessageParser<OpenTerminalChartWithEaReply>(() => new OpenTerminalChartWithEaReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenTerminalChartWithEaReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaReply(OpenTerminalChartWithEaReply other) : this() {
      switch (other.ResponseCase) {
        case ResponseOneofCase.Data:
          Data = other.Data.Clone();
          break;
        case ResponseOneofCase.Error:
          Error = other.Error.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaReply Clone() {
      return new OpenTerminalChartWithEaReply(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::mt4_term_api.OpenTerminalChartWithEaData Data {
      get { return responseCase_ == ResponseOneofCase.Data ? (global::mt4_term_api.OpenTerminalChartWithEaData) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Data;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mt4TermApi.Error Error {
      get { return responseCase_ == ResponseOneofCase.Error ? (global::Mt4TermApi.Error) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Error;
      }
    }

    private object response_;
    /// <summary>Enum of possible cases for the "response" oneof.</summary>
    public enum ResponseOneofCase {
      None = 0,
      Data = 1,
      Error = 2,
    }
    private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseOneofCase ResponseCase {
      get { return responseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponse() {
      responseCase_ = ResponseOneofCase.None;
      response_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenTerminalChartWithEaReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenTerminalChartWithEaReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      if (!object.Equals(Error, other.Error)) return false;
      if (ResponseCase != other.ResponseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (responseCase_ == ResponseOneofCase.Data) hash ^= Data.GetHashCode();
      if (responseCase_ == ResponseOneofCase.Error) hash ^= Error.GetHashCode();
      hash ^= (int) responseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (responseCase_ == ResponseOneofCase.Data) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (responseCase_ == ResponseOneofCase.Data) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (responseCase_ == ResponseOneofCase.Data) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenTerminalChartWithEaReply other) {
      if (other == null) {
        return;
      }
      switch (other.ResponseCase) {
        case ResponseOneofCase.Data:
          if (Data == null) {
            Data = new global::mt4_term_api.OpenTerminalChartWithEaData();
          }
          Data.MergeFrom(other.Data);
          break;
        case ResponseOneofCase.Error:
          if (Error == null) {
            Error = new global::Mt4TermApi.Error();
          }
          Error.MergeFrom(other.Error);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::mt4_term_api.OpenTerminalChartWithEaData subBuilder = new global::mt4_term_api.OpenTerminalChartWithEaData();
            if (responseCase_ == ResponseOneofCase.Data) {
              subBuilder.MergeFrom(Data);
            }
            input.ReadMessage(subBuilder);
            Data = subBuilder;
            break;
          }
          case 18: {
            global::Mt4TermApi.Error subBuilder = new global::Mt4TermApi.Error();
            if (responseCase_ == ResponseOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::mt4_term_api.OpenTerminalChartWithEaData subBuilder = new global::mt4_term_api.OpenTerminalChartWithEaData();
            if (responseCase_ == ResponseOneofCase.Data) {
              subBuilder.MergeFrom(Data);
            }
            input.ReadMessage(subBuilder);
            Data = subBuilder;
            break;
          }
          case 18: {
            global::Mt4TermApi.Error subBuilder = new global::Mt4TermApi.Error();
            if (responseCase_ == ResponseOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OpenTerminalChartWithEaData : pb::IMessage<OpenTerminalChartWithEaData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenTerminalChartWithEaData> _parser = new pb::MessageParser<OpenTerminalChartWithEaData>(() => new OpenTerminalChartWithEaData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenTerminalChartWithEaData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::mt4_term_api.Mt4TermApiChartsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaData(OpenTerminalChartWithEaData other) : this() {
      chartId_ = other.chartId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenTerminalChartWithEaData Clone() {
      return new OpenTerminalChartWithEaData(this);
    }

    /// <summary>Field number for the "chart_id" field.</summary>
    public const int ChartIdFieldNumber = 1;
    private long chartId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ChartId {
      get { return chartId_; }
      set {
        chartId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenTerminalChartWithEaData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenTerminalChartWithEaData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChartId != other.ChartId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChartId != 0L) hash ^= ChartId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChartId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChartId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChartId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChartId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChartId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChartId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenTerminalChartWithEaData other) {
      if (other == null) {
        return;
      }
      if (other.ChartId != 0L) {
        ChartId = other.ChartId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChartId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChartId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
